#!/usr/bin/env bash

set -e
if [ "$(uname -s)" = "Darwin" ];then
  export PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"
  export PATH="/opt/homebrew/opt/gawk/libexec/gnubin:$PATH"
  export PATH="/opt/homebrew/opt/grep/libexec/gnubin:$PATH"
  export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
fi

kill_all_process(){
	ps aux \
	| awk '(\
			$0 ~ "cmdclick" \
				&& $0 !~ "grep" \
		){ 
			printf $2"\t"
		}' \
	| kill $(cat)
}


first_option="${1:-}"
real_path="$(realpath "$0")"
case "${first_option}" in
	"-k") 
		kill_all_process
		exit 0
		;;
	"")
		bash $(dirname "${real_path}")/cmdclick_dir/exec_cmdclick.sh
		exit 0
		;;
esac
bash $(dirname "${real_path}")/cmdclick_dir/exec_cmdclick.sh "${first_option}"
